name: Build Android APK

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Native Android Code (Prebuild)
        run: npx expo prebuild --platform android --clean

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Android APK
        working-directory: ./android
        run: |
          # Reduce APK size by only compiling for arm64 (most modern phones)
          sed -i 's/reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64/reactNativeArchitectures=arm64-v8a/g' gradle.properties
          
          chmod +x gradlew
          ./gradlew assembleRelease -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: almaarifa-apk
          path: android/app/build/outputs/apk/release/app-release.apk
